apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-k8s-basic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: ai-k8s-basic-container
        image: saars/aik8sbasic:latest
        ports:
        - containerPort: 80
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: YOUR-APPINSIGHTS-INSTRUMENTATION-KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ai-k8s-basic
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer
