apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-k8s-app-deployment
  labels:
    app: ai-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-k8s-app
  template:
    metadata:
      labels:
        app: ai-k8s-app
    spec:
      containers:
      - name: ai-k8s-app
        image: dockerhub_account_name/ai-k8s-app:0.0.8
        env:
        # Uncomment the following lines to overwrite the Application Insights Instrumentation Key
        #- name: APPINSIGHTS_INSTRUMENTATIONKEY
        #  value: APPLICATION INSIGHTS KEY OVERWRITE 
        - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
          value: Microsoft.ApplicationInsights.Kubernetes.HostingStartup
