apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-k8s-basic-console
  namespace: ai-k8s-demo
  labels:
    app: consoleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consoleapp
  template:
    metadata:
      labels:
        app: consoleapp
    spec:
      containers:
      - name: ai-k8s-basic-container
        image: containerregistryaccount/basicconsole:1.0.0
