apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-k8s-basic-console
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consoleapp
    spec:
      containers:
      - name: ai-k8s-basic-container
        image: dockeraccount/basicconsole:latest
